### API FLASK ################################################
@url=http://localhost:5000
@authToken = {{login.response.body.data.access_token}}


### Home Url ################################################
GET {{url}}

### Get All Dosen ###########################################
GET {{url}}/dosen
Authorization: Bearer {{authToken}}

### Page Dosen ###########################################
GET {{url}}/api/dosen/page?start=4&limit=3
Authorization: Bearer {{authToken}}


### Save Dosen ##############################################
POST {{url}}/dosen
Authorization: Bearer {{authToken}}
Content-Type: application/x-www-form-urlencoded

nidn=DSN00015
&nama=Azka Nufail
&phone=1234545
&alamat=Bantul

### Get Detail Dosen ########################################
GET {{url}}/dosen/1
Authorization: Bearer {{authToken}}

### Edit Detail Dosen ######################################
PUT {{url}}/dosen/1
Authorization: Bearer {{authToken}}
Content-Type: application/x-www-form-urlencoded

nidn=DSN00001&nama=Bayu Saputro&phone=3333333&alamat=Bantul

### Delete Detail Dosen ####################################
DELETE {{url}}/dosen/5
Authorization: Bearer {{authToken}}

### Create Admin ##########################################
POST {{url}}/create-admin
Authorization: Bearer {{authToken}}
Content-Type: application/x-www-form-urlencoded

name=admin
&password=password
&email=admin@gmail.com

### Login #################################################
# @name login
POST {{url}}/login
Content-Type: application/x-www-form-urlencoded

&password=password
&email=admin@gmail.com

### Protected #############################################
GET {{url}}/protected
Authorization: Bearer {{authToken}}

### Upload ################################################
POST {{url}}/file-upload
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="judul"

test
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.jpeg"
Content-Type: image/jpeg

< ./../test.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
