"""update uniq table dosen dan mahasiswa

Revision ID: 1d629dcce61d
Revises: fc0ef411fa23
Create Date: 2024-07-21 18:37:19.148310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d629dcce61d'
down_revision = 'fc0ef411fa23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dosen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dosen_nidn'), ['nidn'], unique=True)

    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mahasiswa_nim'), ['nim'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mahasiswa_nim'))

    with op.batch_alter_table('dosen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dosen_nidn'))

    # ### end Alembic commands ###
